[package]
name = "mod_prometheus"
version = "0.9.0"
authors = ["Moises Silva <moises.silva@gmail.com>"]
edition = "2024"

[dependencies]
lazy_static = "1.4.0"
libc = "*"
prometheus = { git = "https://github.com/moises-silva/prometheus-rs" }
freeswitchrs = { git = "https://github.com/libon/freeswitchrs" }

[lib]
crate-type = ["dylib"]
name = "mod_prometheus"
path = "mod_prometheus.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
